### ISSUE TITLE
我自己写了一个测试Demo,拿地铁卡,门禁卡,身份证等识别,只弹出系统界面,无法识别卡片信息,你碰到的是同样的情况吗?

### ISSUE THREAD

**Issue by 913868456** [rickierYun/NFCDemo#1]

**Comment by rickierYun** [comment]
iOS现在支持的NFC的芯片有限，所以很多都不能识别，我也是这样的。国内的一些老的公交卡芯片信息应该是读不出来，至于身份证就更加特殊了。未来还要看苹果给出的权限和硬件标准。

**Comment by 913868456** [comment]
我拿北京地铁卡,我们小区的门禁卡,身份证都读不出来,今天突然想写一下CoreNFC的Demo ,研究一下新功能,没想到苹果这么不给力,这么多卡片都不支持,开放这个CoreNFC有什么用,我已经无力吐槽了...

**Comment by rickierYun** [comment]
确实本来想好好玩玩，发现没硬件玩不动。

**Comment by rickierYun** [comment]
有的。Apple的nfc没有全开，所以很多都是识别不了。

发自我的 iPhone
